apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faculty
  template:
    metadata:
      labels:
        app: faculty
    spec:
      containers:
        - name: faculty
          image: faculty-service:latest
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: faculty-service
spec:
  selector:
    app: faculty
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
